name: Package and release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Package and release
        uses: BigWigsMods/packager@master
        with:
          args: -g retail